-- =========================================================================
-- COSTLAB / SUPERBASE: COMPLETE ALL-IN-ONE MASTER DATABASE SCRIPT
-- Run this single script in Supabase Dashboard -> SQL Editor
-- It sets up all tables, columns, indexes, RLS, storage buckets, 
-- RPC functions, system configurations, and the default ADMIN account.
-- Safe to run on fresh databases OR existing databases (Idempotent).
-- =========================================================================

-- =========================================================================
-- 0. EXTENSIONS
-- =========================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =========================================================================
-- 1. TABLES DEFINITIONS
-- =========================================================================

-- 1. Projects Table (โครงการ)
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,                                      -- ID Project (e.g. 1, 2, PRJ-001)
  name TEXT NOT NULL,                                       -- ชื่อ Project
  customer_name TEXT,                                       -- ชื่อลูกค้า
  location TEXT,                                            -- สถานที่
  budget NUMERIC DEFAULT 0,                                 -- งบไม่เกิน
  work_amount NUMERIC DEFAULT 0,                            -- ยอดงาน
  vat_total NUMERIC DEFAULT 0,                              -- ยอดรวม vat
  color TEXT DEFAULT 'Green',                               -- สีสถานะ (Red / Green)
  company TEXT,                                             -- บริษัท
  responsible_person TEXT,                                  -- ผู้รับผิดชอบ
  start_date DATE,                                          -- วันที่เริ่มโครงการ
  data JSONB DEFAULT '{}'::jsonb,                           -- ข้อมูลไดนามิกสำรอง
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Stores Table (ร้านค้า)
CREATE TABLE IF NOT EXISTS public.stores (
  id TEXT PRIMARY KEY,                                      -- id_store
  name TEXT NOT NULL,                                       -- ชื่อร้านค้า
  full_name TEXT,                                           -- ชื่อเต็ม
  bank_name TEXT,                                           -- ชื่อธนาคาร
  bank_account TEXT,                                        -- เลขบัญชี
  phone TEXT,                                               -- เบอร์โทร
  address TEXT,                                             -- ที่อยู่
  tax_id TEXT,                                              -- เลขที่ผู้เสียภาษี
  data JSONB DEFAULT '{}'::jsonb
);

-- 3. Contractors Table (รับเหมา)
CREATE TABLE IF NOT EXISTS public.contractors (
  id TEXT PRIMARY KEY,                                      -- id_Contractor
  nickname TEXT,                                            -- ชื่อเล่น
  full_name TEXT,                                           -- ชื่อ-นามสกุล
  bank_name TEXT,                                           -- ชื่อธนาคาร
  bank_account TEXT,                                        -- เลขบัญชี
  id_card TEXT,                                             -- บัตรประจำตัวประชาชน
  phone TEXT,                                               -- เบอร์โทรศัพท์
  address TEXT,                                             -- ที่อยู่
  annual_limit NUMERIC DEFAULT 0,                           -- จำกัดยอด/ปี
  data JSONB DEFAULT '{}'::jsonb
);

-- 4. Contract Works Table (งานรับเหมา / เปิดจ้าง)
CREATE TABLE IF NOT EXISTS public.contract_works (
  id TEXT PRIMARY KEY,                                      -- id_Conwork (e.g. CW1, CW2)
  contractor_id TEXT REFERENCES public.contractors(id) ON DELETE SET NULL,
  project_id TEXT REFERENCES public.projects(id) ON DELETE SET NULL,
  project_name TEXT,
  total_contract_amount NUMERIC DEFAULT 0,                  -- ยอดเงินจ้าง
  work_details TEXT,                                        -- รายละเอียดงาน
  work_date DATE,                                           -- วันที่
  phone TEXT,                                               -- เบอร์โทรศัพท์
  paid_amount NUMERIC DEFAULT 0,                            -- ยอดเงินจ่าย
  data JSONB DEFAULT '{}'::jsonb
);

-- 5. Bills Table (กรอกบิล / เบิกเงิน)
CREATE TABLE IF NOT EXISTS public.bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- ลำดับ
  project_id TEXT REFERENCES public.projects(id) ON DELETE SET NULL,
  project_name TEXT,
  bill_type TEXT DEFAULT 'หลัก',                             -- ประเภทบิล (หลัก, ย่อย, หลัก2, ย่อย2)
  vendor_or_person TEXT,                                    -- ร้าน/บุคคล / ร้านค้า
  description TEXT,                                         -- สินค้า/ทำงาน
  bill_no TEXT,                                             -- เลขที่บิล / No.
  category TEXT,                                            -- ประเภท
  sub_category TEXT,                                        -- ประเภทหมวดย่อย
  amount NUMERIC DEFAULT 0,                                 -- ยอดเงิน / ยอดเบิก
  vat_amount NUMERIC DEFAULT 0,                             -- vat
  withholding_tax NUMERIC DEFAULT 0,                        -- หัก
  credit_days INTEGER DEFAULT 0,                            -- เครดิต
  requester TEXT,                                           -- ผู้เบิก
  bill_date DATE,                                           -- ว/ด/ป
  image_url TEXT,                                           -- รูปถ่ายบิล (Supabase Storage Public URL)
  status TEXT DEFAULT 'ตั้งเบิก',                              -- สถานะ (ตั้งเบิก, อนุมัติ, เบิกแล้ว, รอตรวจสอบ)
  bill_received_date DATE,                                  -- วันได้บิล
  wht_issued_date DATE,                                     -- วันออก 3%
  paid_date DATE,                                           -- วันจ่าย
  labor_status TEXT,                                        -- สถานะค่าแรง (บุคคลธรรมดา / บริษัท)
  transfer_amount NUMERIC DEFAULT 0,                        -- ยอดโอน
  material_cost NUMERIC DEFAULT 0,                          -- ค่าของ
  labor_cost NUMERIC DEFAULT 0,                             -- ค่าแรง
  staff_cost NUMERIC DEFAULT 0,                             -- พนักงาน
  fuel_cost NUMERIC DEFAULT 0,                              -- น้ำมัน
  repair_cost NUMERIC DEFAULT 0,                            -- ซ่อมรถ
  machine_cost NUMERIC DEFAULT 0,                           -- เครื่องจักร
  tool_cost NUMERIC DEFAULT 0,                              -- เครื่องมือ
  other_cost NUMERIC DEFAULT 0,                             -- อื่นๆ
  created_by TEXT,                                          -- ผู้สร้างบิล
  approved_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tasks Table (งานทั่วไป - สำหรับ LINE Bot)
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,                                      -- รายการ
  do_date DATE,                                             -- ดู/ทำ
  send_date DATE,                                           -- ส่งงาน
  assignee_id TEXT,                                         -- รหัสพนักงาน
  assignee_name TEXT,                                       -- ผู้รับผิดชอบ
  status TEXT DEFAULT 'ดำเนินการ',                            -- สถานะ (ดำเนินการ / สำเร็จ)
  task_type INTEGER DEFAULT 1,                              -- ประเภทงาน (1: เอกสาร, 2: แผนงาน, 3: PJSA)
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Works Table (งาน PW / มอบหมาย - สำหรับ LINE Bot)
CREATE TABLE IF NOT EXISTS public.works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team TEXT NOT NULL DEFAULT 'PW',                          -- ทีม (PW, PW1, PW2, PW3, PW4)
  activity_type TEXT,                                       -- กิจกรรม (เสนอราคา, ประชุมงาน, ประมูล)
  title TEXT,                                               -- เรื่อง
  pr_no TEXT,                                               -- PR
  location TEXT,                                            -- สถานที่
  date_inspect TEXT,                                        -- นัดดู
  date_propose TEXT,                                        -- นัดเสนอ
  contact1 TEXT,                                            -- ติดต่อ1
  phone1 TEXT,                                              -- เบอร์1
  contact2 TEXT,                                            -- ติดต่อ2
  phone2 TEXT,                                              -- เบอร์2
  company TEXT,                                             -- บริษัท
  status TEXT DEFAULT 'รอดูงาน',                              -- สถานะ (รอดูงาน, รอเสนอ, ส่งแล้ว, ประชุม, ฯลฯ)
  note TEXT,                                                -- หมายเหตุ
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Plans Table (แผนงาน - สำหรับ LINE Bot)
CREATE TABLE IF NOT EXISTS public.plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code TEXT,                                        -- รหัสงาน
  job_name TEXT,                                            -- ชื่อแผนงาน
  item_name TEXT,                                           -- รายการ
  start_date DATE,                                          -- วันที่เริ่ม
  end_date DATE,                                            -- วันที่จบ
  days_count INTEGER DEFAULT 0,
  plan_percentage NUMERIC DEFAULT 0,
  actual_percentage NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Open',
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Master Members Table (รายชื่อพนักงาน & สิทธิ์การใช้งาน)
CREATE TABLE IF NOT EXISTS public.master_members (
  id TEXT PRIMARY KEY,                                      -- รหัสพนักงาน (e.g. admin, PT101)
  nickname TEXT,                                            -- ชื่อเล่น
  full_name TEXT,                                           -- ชื่อ-นามสกุล
  bank_name TEXT,                                           -- ชื่อธนาคาร
  bank_account TEXT,                                        -- เลขบัญชี
  phone TEXT,                                               -- เบอร์โทร
  address TEXT,                                             -- ที่อยู่
  id_card TEXT,                                             -- เลขบัตรประชาชน
  role TEXT,                                                -- สิทธิ์การใช้งานแบบเดิม (Admin, Manager, User)
  system_role TEXT DEFAULT 'User',                          -- สิทธิ์ระบบละเอียด (Admin_Approver, Admin_Closer, Admin, User)
  status TEXT DEFAULT 'Active',                             -- สถานะ (Active / Inactive)
  is_owner BOOLEAN DEFAULT false,                           -- เจ้าของระบบ (Owner) รับแจ้งเตือนหลัก
  can_approve BOOLEAN DEFAULT false,                        -- สิทธิ์ฝ่ายการเงิน / ปิดบิล & ยืนยันจ่ายเงิน
  can_close_bill BOOLEAN DEFAULT false,                     -- สิทธิ์อนุมัติบิล (Approver) รับแจ้งเตือนและกดอนุมัติ
  can_delete BOOLEAN DEFAULT false,                         -- สิทธิ์ลบข้อมูลบิลและโครงการ
  line_user_id TEXT,                                        -- LINE User ID
  pictureUrl TEXT,                                          -- รูปโปรไฟล์
  data JSONB DEFAULT '{}'::jsonb
);

-- 10. Banks Table (ธนาคาร)
CREATE TABLE IF NOT EXISTS public.banks (
  id TEXT PRIMARY KEY,                                      -- id_bank (e.g. Ba101)
  name TEXT NOT NULL,                                       -- ชื่อธนาคาร
  image TEXT,                                               -- โลโก้ธนาคาร
  data JSONB DEFAULT '{}'::jsonb
);

-- 11. Cars Table (ทะเบียนรถ)
CREATE TABLE IF NOT EXISTS public.cars (
  id TEXT PRIMARY KEY,                                      -- id_car
  plate_no TEXT NOT NULL,                                   -- หมายเลขทะเบียน
  brand TEXT,                                               -- ยี่ห้อรถ
  color TEXT,                                               -- สี
  responsible_person TEXT,                                  -- รับผิดชอบ
  owner TEXT,                                               -- รถของ
  data JSONB DEFAULT '{}'::jsonb
);

-- 12. Categories Table (ประเภท)
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name1 TEXT,
  name2 TEXT,
  name3 TEXT,
  data JSONB DEFAULT '{}'::jsonb
);

-- 13. Customers Table (ลูกค้า)
CREATE TABLE IF NOT EXISTS public.customers (
  id TEXT PRIMARY KEY,                                      -- id_cus
  name TEXT NOT NULL,                                       -- ชื่อลูกค้า
  address TEXT,                                             -- ที่อยู่
  tax_id TEXT,                                              -- เลขที่ผู้เสียภาษี
  data JSONB DEFAULT '{}'::jsonb
);

-- 14. Companies Table (บริษัท)
CREATE TABLE IF NOT EXISTS public.companies (
  id TEXT PRIMARY KEY,                                      -- id_Company
  name_en TEXT,                                             -- ชื่ออังกฤษ
  name_th TEXT NOT NULL,                                    -- ชื่อบริษัท
  branch TEXT,                                              -- สำนักงาน
  address TEXT,                                             -- ที่อยู่
  tax_id TEXT,                                              -- เลขที่ผู้เสียภาษี
  phone TEXT,                                               -- เบอร์โทร
  data JSONB DEFAULT '{}'::jsonb
);

-- 15. Loans Table (ยืมเงิน)
CREATE TABLE IF NOT EXISTS public.loans (
  id TEXT PRIMARY KEY,                                      -- id
  borrower_name TEXT,                                       -- ชื่อ
  type TEXT,                                                -- type
  amount NUMERIC DEFAULT 0,                                 -- จำนวนเงิน
  loan_date DATE,                                           -- วันที่
  data JSONB DEFAULT '{}'::jsonb
);

-- 16. Products Table (สินค้า)
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,                                      -- id_product
  name TEXT NOT NULL,                                       -- ชื่อสินค้า
  category TEXT,                                            -- หมวดหมู่
  unit TEXT,                                                -- หน่วยนับ
  price NUMERIC DEFAULT 0,                                  -- ราคาต่อหน่วย
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 17. System Options Table (ตัวเลือกระบบ & การตั้งค่า JSONB)
CREATE TABLE IF NOT EXISTS public.system_options (
  id TEXT PRIMARY KEY DEFAULT 'system_options',
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 18. Audit Logs Table (ระบบ Log ประวัติการแก้ไข)
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,                                     -- CREATE, UPDATE, DELETE
  table_name TEXT NOT NULL,
  record_id TEXT,
  changed_by TEXT,
  old_data JSONB,
  new_data JSONB,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 2. SAFETY COLUMN UPDATES (Ensure existing tables have all columns)
-- =========================================================================
ALTER TABLE IF EXISTS public.bills 
  ADD COLUMN IF NOT EXISTS bill_received_date DATE,
  ADD COLUMN IF NOT EXISTS wht_issued_date DATE,
  ADD COLUMN IF NOT EXISTS paid_date DATE,
  ADD COLUMN IF NOT EXISTS labor_status TEXT,
  ADD COLUMN IF NOT EXISTS transfer_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS material_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS labor_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS staff_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fuel_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS repair_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS machine_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tool_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;

ALTER TABLE IF EXISTS public.stores 
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;

ALTER TABLE IF EXISTS public.contractors 
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;

ALTER TABLE IF EXISTS public.master_members 
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS line_user_id TEXT,
  ADD COLUMN IF NOT EXISTS pictureUrl TEXT,
  ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;

ALTER TABLE IF EXISTS public.projects 
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS work_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS start_date DATE,
  ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;

-- Unlock Identity sequences for manual and auto-increment insertion
ALTER TABLE IF EXISTS public.bills ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.tasks ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.works ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.plans ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.categories ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.audit_logs ALTER COLUMN id SET GENERATED BY DEFAULT;

-- =========================================================================
-- 3. HIGH-PERFORMANCE COMPOSITE & FILTER INDEXES
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_bills_project_id ON public.bills(project_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON public.bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_date ON public.bills(bill_date);
CREATE INDEX IF NOT EXISTS idx_bills_requester ON public.bills(requester);
CREATE INDEX IF NOT EXISTS idx_bills_created_at ON public.bills(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bills_category ON public.bills(category);
CREATE INDEX IF NOT EXISTS idx_bills_vendor_or_person ON public.bills(vendor_or_person);

-- Composite query indexes
CREATE INDEX IF NOT EXISTS idx_bills_status_project ON public.bills(status, project_id);
CREATE INDEX IF NOT EXISTS idx_bills_date_status ON public.bills(bill_date DESC, status);
CREATE INDEX IF NOT EXISTS idx_bills_requester_status ON public.bills(requester, status);
CREATE INDEX IF NOT EXISTS idx_bills_project_date ON public.bills(project_id, bill_date DESC);
CREATE INDEX IF NOT EXISTS idx_bills_received_date ON public.bills(bill_received_date);
CREATE INDEX IF NOT EXISTS idx_bills_wht_date ON public.bills(wht_issued_date);
CREATE INDEX IF NOT EXISTS idx_bills_paid_date ON public.bills(paid_date);

CREATE INDEX IF NOT EXISTS idx_contract_works_project ON public.contract_works(project_id);
CREATE INDEX IF NOT EXISTS idx_contract_works_contractor ON public.contract_works(contractor_id);
CREATE INDEX IF NOT EXISTS idx_contract_works_project_contractor ON public.contract_works(project_id, contractor_id);
CREATE INDEX IF NOT EXISTS idx_contract_works_work_date ON public.contract_works(work_date DESC);

CREATE INDEX IF NOT EXISTS idx_projects_name ON public.projects(name);
CREATE INDEX IF NOT EXISTS idx_projects_color ON public.projects(color);
CREATE INDEX IF NOT EXISTS idx_master_members_phone ON public.master_members(phone);
CREATE INDEX IF NOT EXISTS idx_master_members_line_id ON public.master_members(line_user_id);
CREATE INDEX IF NOT EXISTS idx_system_options_id ON public.system_options(id);
CREATE INDEX IF NOT EXISTS idx_tasks_status_assignee ON public.tasks(status, assignee_id);
CREATE INDEX IF NOT EXISTS idx_works_team_status ON public.works(team, status);

-- =========================================================================
-- 4. ROW LEVEL SECURITY (RLS) & ACCESS POLICIES
-- =========================================================================
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contractors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'projects', 'stores', 'contractors', 'contract_works', 'bills', 
    'tasks', 'works', 'plans', 'master_members', 'banks', 'cars', 
    'categories', 'customers', 'companies', 'loans', 'products', 
    'system_options', 'audit_logs'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Public Read Access %I" ON public.%I;', t, t);
    EXECUTE format('DROP POLICY IF EXISTS "Public Write Access %I" ON public.%I;', t, t);
    EXECUTE format('CREATE POLICY "Public Read Access %I" ON public.%I FOR SELECT USING (true);', t, t);
    EXECUTE format('CREATE POLICY "Public Write Access %I" ON public.%I FOR ALL USING (true) WITH CHECK (true);', t, t);
  END LOOP;
END $$;

-- =========================================================================
-- 5. SUPABASE STORAGE BUCKETS & STORAGE RLS POLICIES
-- =========================================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('bills', 'bills', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('attachments', 'attachments', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Read Access for Bills Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Access for Bills Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Access for Bills Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Access for Bills Bucket" ON storage.objects;

DROP POLICY IF EXISTS "Public Read Access for Attachments Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Access for Attachments Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Access for Attachments Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Access for Attachments Bucket" ON storage.objects;

CREATE POLICY "Public Read Access for Bills Bucket" ON storage.objects FOR SELECT USING (bucket_id = 'bills');
CREATE POLICY "Public Insert Access for Bills Bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'bills');
CREATE POLICY "Public Update Access for Bills Bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'bills');
CREATE POLICY "Public Delete Access for Bills Bucket" ON storage.objects FOR DELETE USING (bucket_id = 'bills');

CREATE POLICY "Public Read Access for Attachments Bucket" ON storage.objects FOR SELECT USING (bucket_id = 'attachments');
CREATE POLICY "Public Insert Access for Attachments Bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'attachments');
CREATE POLICY "Public Update Access for Attachments Bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'attachments');
CREATE POLICY "Public Delete Access for Attachments Bucket" ON storage.objects FOR DELETE USING (bucket_id = 'attachments');

-- =========================================================================
-- 6. HIGH-SPEED METRICS RPC FUNCTION
-- =========================================================================
CREATE OR REPLACE FUNCTION get_dashboard_metrics()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result JSONB;
    v_total_bills BIGINT;
    v_total_amount NUMERIC;
    v_total_projects BIGINT;
    v_pending_bills BIGINT;
BEGIN
    SELECT 
        COUNT(*),
        COALESCE(SUM(amount), 0),
        COUNT(CASE WHEN status = 'ตั้งเบิก' OR status = 'รอตั้งเบิก' OR status = 'รออนุมัติ' THEN 1 END)
    INTO v_total_bills, v_total_amount, v_pending_bills
    FROM public.bills;

    SELECT COUNT(*) INTO v_total_projects FROM public.projects;

    result := jsonb_build_object(
        'total_bills', v_total_bills,
        'total_amount', v_total_amount,
        'pending_bills', v_pending_bills,
        'total_projects', v_total_projects,
        'generated_at', now()
    );

    RETURN result;
END;
$$;

-- 6.2 HIGH-SPEED FINANCIAL AGGREGATE RPC FUNCTION
CREATE OR REPLACE FUNCTION get_dashboard_financial_summary(
    p_start_date DATE DEFAULT NULL,
    p_end_date DATE DEFAULT NULL,
    p_project_id TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result JSONB;
    v_total_bills BIGINT;
    v_total_amount NUMERIC;
    v_total_material NUMERIC;
    v_total_labor NUMERIC;
    v_total_staff NUMERIC;
    v_total_fuel NUMERIC;
    v_total_repair NUMERIC;
    v_total_machine NUMERIC;
    v_total_tool NUMERIC;
    v_total_other NUMERIC;
    v_total_vat NUMERIC;
    v_total_wht NUMERIC;
    v_total_transfer NUMERIC;
    v_status_pending BIGINT;
    v_status_requested BIGINT;
    v_status_approved BIGINT;
    v_status_paid BIGINT;
BEGIN
    SELECT 
        COUNT(*),
        COALESCE(SUM(amount), 0),
        COALESCE(SUM(material_cost), 0),
        COALESCE(SUM(labor_cost), 0),
        COALESCE(SUM(staff_cost), 0),
        COALESCE(SUM(fuel_cost), 0),
        COALESCE(SUM(repair_cost), 0),
        COALESCE(SUM(machine_cost), 0),
        COALESCE(SUM(tool_cost), 0),
        COALESCE(SUM(other_cost), 0),
        COALESCE(SUM(vat_amount), 0),
        COALESCE(SUM(withholding_tax), 0),
        COALESCE(SUM(transfer_amount), 0),
        COUNT(CASE WHEN status = 'รออนุมัติ' OR status = 'รอตรวจสอบ' THEN 1 END),
        COUNT(CASE WHEN status = 'ตั้งเบิก' OR status = 'รอตั้งเบิก' THEN 1 END),
        COUNT(CASE WHEN status = 'อนุมัติ' THEN 1 END),
        COUNT(CASE WHEN status = 'เบิกแล้ว' OR status = 'ปิดงาน' THEN 1 END)
    INTO 
        v_total_bills,
        v_total_amount,
        v_total_material,
        v_total_labor,
        v_total_staff,
        v_total_fuel,
        v_total_repair,
        v_total_machine,
        v_total_tool,
        v_total_other,
        v_total_vat,
        v_total_wht,
        v_total_transfer,
        v_status_pending,
        v_status_requested,
        v_status_approved,
        v_status_paid
    FROM public.bills
    WHERE 
        (p_start_date IS NULL OR bill_date >= p_start_date) AND
        (p_end_date IS NULL OR bill_date <= p_end_date) AND
        (p_project_id IS NULL OR project_id = p_project_id);

    result := jsonb_build_object(
        'total_bills', v_total_bills,
        'total_amount', v_total_amount,
        'material_cost', v_total_material,
        'labor_cost', v_total_labor,
        'staff_cost', v_total_staff,
        'fuel_cost', v_total_fuel,
        'repair_cost', v_total_repair,
        'machine_cost', v_total_machine,
        'tool_cost', v_total_tool,
        'other_cost', v_total_other,
        'vat_amount', v_total_vat,
        'withholding_tax', v_total_wht,
        'transfer_amount', v_total_transfer,
        'status_counts', jsonb_build_object(
            'pending', v_status_pending,
            'requested', v_status_requested,
            'approved', v_status_approved,
            'paid', v_status_paid
        ),
        'generated_at', now()
    );

    RETURN result;
END;
$$;

-- =========================================================================
-- 7. INITIAL MASTER SEED DATA (ADMIN ACCOUNT 0800000000 / admin)
-- =========================================================================

-- 7.1 สร้าง Admin ในตารางพนักงาน (master_members)
INSERT INTO public.master_members (id, nickname, full_name, bank_account, phone, address, id_card, role)
VALUES 
  ('admin', 'Admin', 'ผู้ดูแลระบบ (Admin)', '-', '0800000000', '-', '-', 'Admin')
ON CONFLICT (id) DO UPDATE SET 
  nickname = EXCLUDED.nickname,
  full_name = EXCLUDED.full_name,
  phone = EXCLUDED.phone,
  role = EXCLUDED.role;

-- 7.2 สร้าง User List ใน system_options
INSERT INTO public.system_options (id, data, updated_at)
VALUES (
  'users_list',
  '[
    {
      "id": "admin",
      "username": "admin",
      "displayName": "ผู้ดูแลระบบ (Admin)",
      "role": "Admin",
      "status": "Active",
      "phone": "0800000000",
      "lineUserId": "",
      "pictureUrl": "",
      "createdAt": "2026-08-22"
    }
  ]'::jsonb,
  timezone('utc'::text, now())
)
ON CONFLICT (id) DO UPDATE SET
  data = CASE 
    WHEN jsonb_typeof(system_options.data) != 'array' THEN EXCLUDED.data
    WHEN NOT (system_options.data @> '[{"username": "admin"}]'::jsonb) AND NOT (system_options.data @> '[{"id": "admin"}]'::jsonb) THEN 
      system_options.data || '[{"id": "admin", "username": "admin", "displayName": "ผู้ดูแลระบบ (Admin)", "role": "Admin", "status": "Active", "phone": "0800000000", "lineUserId": "", "pictureUrl": "", "createdAt": "2026-08-22"}]'::jsonb
    ELSE system_options.data
  END,
  updated_at = timezone('utc'::text, now());

-- 7.3 ข้อมูลการตั้งค่าระบบ (Dropdown Options)
INSERT INTO public.system_options (id, data, updated_at)
VALUES (
  'system_options',
  '{
    "vat": ["VAT 7%"],
    "หัก": ["หัก 1%","หัก 2%","หัก 3%", "หัก 5%"],
    "เครดิต": ["15 วัน", "30 วัน", "60 วัน"],
    "ประเภทบิล": ["หลัก", "ย่อย"],
    "statusค่าแรง": ["บุคคลธรรมดา", "บริษัท"],
    "ยี่ห้อรถ": ["Toyota", "Isuzu", "Ford", "Mitsubishi", "Nissan", "Honda", "MG", "Mazda"],
    "รับผิดชอบ": ["PW1", "PW2", "PW3", "PW4", "PW"],
    "รายละเอียดงาน": [
      "งานฐานราก/เสาเข็ม",
      "งานโครงสร้าง/ผูกเหล็ก/เข้าแบบ",
      "งานเทคอนกรีต",
      "งานมุงหลังคา/กันสาด",
      "งานก่ออิฐ/ฉาบปูน",
      "งานปูกระเบื้อง/พื้น",
      "งานระบบไฟฟ้า",
      "งานระบบประปา/สุขาภิบาล",
      "งานสีและเคมี",
      "งานประตู/หน้าต่าง/กระจก",
      "งานบิวท์อิน/ตกแต่ง"
    ],
    "ชื่อเครื่องมือ": [
      "สว่านเจาะเหล็กไฟฟ้า",
      "สว่านเจาะปูน Rotary",
      "ลูกหมูขนาด 4\"",
      "ลูกหมูขนาด 7\"",
      "ไฟเบอร์ตัดเหล็ก"
    ],
    "ประเภท (ร้านค้า)": ["4.น้ำมัน", "5.ซ่อมรถ", "6.เครื่องจักร"],
    "ประเภท (ผู้รับเหมา)": ["2.ค่าแรง", "3.พนักงาน", "8.อื่นๆ"],
    "รายการประเภททั้งหมด": [
      "1.ค่าของ",
      "2.ค่าแรง",
      "3.พนักงาน",
      "4.น้ำมัน",
      "5.ซ่อมรถ",
      "6.เครื่องจักร",
      "7.เครื่องมือ",
      "8.อื่นๆ"
    ],
    "ประเภท (ร้านค้า+เลือกสินค้า)": ["1.ค่าของ", "7.เครื่องมือ", "8.อื่นๆ"],
    "bill_start_sequence": 1,
    "ลำดับบิลเริ่มต้น": 1,
    "PRODUCT_MASTER_DATA": [
      {"id": "1", "code": "1", "name": "ปูน/ทราย/หิน", "group": "หมวดงานโครงสร้าง", "active": true, "description": "ปูนซีเมนต์, ปูนกาว, ทรายหยาบ/ละเอียด, หิน 1-2"},
      {"id": "2", "code": "2", "name": "เหล็กเส้น/รูปพรรณ", "group": "หมวดงานโครงสร้าง", "active": true, "description": "เหล็กข้ออ้อย, เหล็กกล่อง, ไวด์แฟรงก์, ตะแกรง wiremesh"},
      {"id": "3", "code": "3", "name": "คอนกรีตผสมเสร็จ", "group": "หมวดงานโครงสร้าง", "active": true, "description": "คอนกรีต Ready-mixed 240-400 ksc"},
      {"id": "4", "code": "4", "name": "ไม้แบบ/ไม้อัด", "group": "หมวดงานโครงสร้าง", "active": true, "description": "ไม้แบบอัด, ไม้แปรรูป, ยูคล้อง"},
      {"id": "5", "code": "5", "name": "วัสดุมุง", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "กระเบื้องหลังคา, เมทัลชีท"},
      {"id": "6", "code": "6", "name": "ฝ้าผนัง", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "แผ่นยิปซัม, สมาร์ทบอร์ด, อิฐก่อ"},
      {"id": "7", "code": "7", "name": "ปูพื้น", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "กระเบื้องยาง, แกรนิตโต้, ไม้ลามิเนต"},
      {"id": "8", "code": "8", "name": "กระจก", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "กระจกอลูมิเนียม, กระจกเทมเปอร์"},
      {"id": "9", "code": "9", "name": "ไฟฟ้า", "group": "หมวดงานระบบ M&E", "active": true, "description": "สายไฟ, ตู้ควบคุม, หลอดไฟ, ท่อร้อยสาย"},
      {"id": "10", "code": "10", "name": "ประปา", "group": "หมวดงานระบบ M&E", "active": true, "description": "ท่อ PVC, ถังเก็บน้ำ, ปั๊มน้ำ"},
      {"id": "11", "code": "11", "name": "อื่นๆ(วัสดุ)", "group": "หมวดงานทั่วไป & ดำเนินการ", "active": true, "description": "วัสดุสิ้นเปลืองทั่วไป"},
      {"id": "12", "code": "12", "name": "สีเคมี", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "สีทาภายใน/นอก, เคมีภัณฑ์กันซึม"},
      {"id": "13", "code": "13", "name": "สุขภัณฑ์", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "โถส้วม, อ่างล้างหน้า, ก๊อกน้ำ"},
      {"id": "14", "code": "14", "name": "บิวอิน", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "เฟอร์นิเจอร์สั่งทำ, ตู้บิวท์อิน"},
      {"id": "15", "code": "15", "name": "แอร์", "group": "หมวดงานระบบ M&E", "active": true, "description": "เครื่องปรับอากาศ, ท่อน้ำยา"},
      {"id": "16", "code": "16", "name": "ดิน", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ดินถม, ดินลูกรัง"},
      {"id": "17", "code": "17", "name": "หินทราย", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "หิน 1-2, ทรายหยาบ/ละเอียด"},
      {"id": "18", "code": "18", "name": "เตรียมงาน", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ป้ายโครงการ, นั่งร้าน, รั้วชั่วคราว"},
      {"id": "101", "code": "101", "name": "น้ำมัน", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "น้ำมันดีเซล/เบนซิน เครื่องจักรและยานพาหนะ"},
      {"id": "102", "code": "102", "name": "ค่าขนส่ง", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ค่าขนส่งสินค้า, ค่ารถสิบล้อ"},
      {"id": "103", "code": "103", "name": "เครื่องจักร", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ค่าเช่าแบคโฮ, เครน, เครื่องปั่นไฟ"},
      {"id": "200", "code": "200", "name": "ดำเนินการ(อื่นๆ)", "group": "หมวดงานทั่วไป & ดำเนินการ", "active": true, "description": "ค่าใช้จ่ายดำเนินงานอื่นๆ"}
    ]
  }'::jsonb,
  timezone('utc'::text, now())
)
ON CONFLICT (id) DO UPDATE SET
  data = EXCLUDED.data,
  updated_at = timezone('utc'::text, now());

-- 7.4 ข้อมูลชื่อบริษัท (Company Settings)
INSERT INTO public.system_options (id, data, updated_at)
VALUES (
  'company_settings',
  '{
    "companyName": "POWERTEC",
    "companySubTitle": "ระบบบริหารและติดตามงบประมาณก่อสร้าง",
    "email": "contact@company.com",
    "phone": "02-123-4567",
    "taxId": "0105560000000",
    "address": "123/45",
    "logoUrl": ""
  }'::jsonb,
  timezone('utc'::text, now())
)
ON CONFLICT (id) DO UPDATE SET
  data = EXCLUDED.data,
  updated_at = timezone('utc'::text, now());

-- 7.5 ข้อมูลธนาคารเริ่มต้น (Default Banks)
INSERT INTO public.banks (id, name, image)
VALUES 
  ('Ba101', 'ธนาคารกสิกรไทย', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/kbank.png'),
  ('Ba102', 'ธนาคารไทยพาณิชย์', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/scb.png'),
  ('Ba103', 'ธนาคารกรุงเทพ', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/bbl.png'),
  ('Ba104', 'ธนาคารกรุงไทย', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/ktb.png'),
  ('Ba105', 'ธนาคารทหารไทยธนชาต', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/ttb.png'),
  ('Ba106', 'ธนาคารกรุงศรีอยุธยา', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/bay.png'),
  ('Ba107', 'ธนาคารออมสิน', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/gsb.png')
ON CONFLICT (id) DO NOTHING;

-- =========================================================================
-- 8. AUTOMATED BACKFILL FROM LEGACY JSONB
-- =========================================================================
DO $$
DECLARE
    v_data JSONB;
    v_key TEXT;
    v_val JSONB;
    v_num_id BIGINT;
    v_rec_date DATE;
    v_wht_date DATE;
    v_paid_date DATE;
BEGIN
    SELECT data INTO v_data FROM public.system_options WHERE id = 'bill_follow_dates';
    IF v_data IS NOT NULL AND jsonb_typeof(v_data) = 'object' THEN
        FOR v_key, v_val IN SELECT * FROM jsonb_each(v_data)
        LOOP
            BEGIN
                IF v_key ~ '^[0-9]+$' THEN
                    v_num_id := v_key::BIGINT;
                    v_rec_date := CASE WHEN (v_val->>'วันได้บิล') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' THEN (v_val->>'วันได้บิล')::DATE ELSE NULL END;
                    v_wht_date := CASE WHEN (v_val->>'วันออก 3%') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' THEN (v_val->>'วันออก 3%')::DATE ELSE NULL END;
                    v_paid_date := CASE WHEN (v_val->>'วันจ่าย') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' THEN (v_val->>'วันจ่าย')::DATE ELSE NULL END;

                    UPDATE public.bills
                    SET 
                        bill_received_date = COALESCE(bills.bill_received_date, v_rec_date),
                        wht_issued_date = COALESCE(bills.wht_issued_date, v_wht_date),
                        paid_date = COALESCE(bills.paid_date, v_paid_date),
                        labor_status = COALESCE(bills.labor_status, v_val->>'statusค่าแรง'),
                        created_by = COALESCE(bills.created_by, v_val->>'ผู้สร้างบิล', v_val->>'created_by')
                    WHERE id = v_num_id;
                END IF;
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
        END LOOP;
    END IF;
END $$;

-- =========================================================================
-- 8. PERFORMANCE INDEXES, STORAGE BUCKET & REALTIME PUBLICATION
-- =========================================================================

-- 8.1 Critical B-Tree Indexes for Fast Filtering & Joins
CREATE INDEX IF NOT EXISTS idx_bills_status ON public.bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_project_id ON public.bills(project_id);
CREATE INDEX IF NOT EXISTS idx_bills_date ON public.bills(date DESC);
CREATE INDEX IF NOT EXISTS idx_contract_works_project_id ON public.contract_works(project_id);
CREATE INDEX IF NOT EXISTS idx_contract_works_contractor_id ON public.contract_works(contractor_id);
CREATE INDEX IF NOT EXISTS idx_withdraw_requests_status ON public.withdraw_requests(status);
CREATE INDEX IF NOT EXISTS idx_master_members_line_id ON public.master_members(line_user_id);
CREATE INDEX IF NOT EXISTS idx_master_members_phone ON public.master_members(phone);

-- 8.2 Storage Bucket "repairs" Setup (for Bill Images & Attachments)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('repairs', 'repairs', true) 
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Public Read Access repairs'
  ) THEN
    CREATE POLICY "Public Read Access repairs" ON storage.objects FOR SELECT TO public USING (bucket_id = 'repairs');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Anyone Upload Access repairs'
  ) THEN
    CREATE POLICY "Anyone Upload Access repairs" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'repairs');
  END IF;
END $$;

-- 8.3 Enable Realtime Publication for Main Tables
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.bills;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.withdraw_requests;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.contract_works;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- =========================================================================
-- COMPLETION MESSAGE
-- =========================================================================
DO $$
BEGIN
  RAISE NOTICE '=======================================================';
  RAISE NOTICE '✅ Master SuperBase Migration Completed Successfully!';
  RAISE NOTICE '👉 All 18 Tables, Indexes, RLS, Storage Buckets, and';
  RAISE NOTICE '👉 Admin account "0800000000" / "admin" are Ready!';
  RAISE NOTICE '=======================================================';
END $$;

